# This is Conda environment file
# Usage: `conda env update -f environment.yml`

name: argoverse
channels:
  - defaults
  - conda-forge

dependencies:
 - pip
 - colour
 - descartes
 - imageio
 - matplotlib
 - numpy==1.19
 - pillow
 - imageio
 - scipy>=1.4.0
 - shapely
 - typing_extensions
 - h5py
 - lap
 - cython
 - pip:
   - sklearn
   - opencv-python>=4.1.0.25
   - motmetrics==1.1.3
   - pyntcloud==0.1.0
