# This is Conda environment file
# Usage: `conda env update -f environment.yml`

name: argoverse
channels:
  - defaults
  - conda-forge

dependencies:
 - python>=3.7
 - pip
 - colour
 - descartes
 - imageio
 - matplotlib
 - numpy==1.19
 - pandas>=0.23.1
 - pillow
 - imageio
 - scipy>=1.4.0
 - shapely
 - sklearn
 - typing_extensions
 - h5py
 - lap
 - pip:
   - opencv-python>=4.1.0.25
   - motmetrics==1.1.3
   - git+https://github.com/daavoo/pyntcloud#egg=pyntcloud-0.1.0
